default:
  data_preparation:
    # The name of the cohort
    cohort_name: "newborns"
    mortality_name: "scratch/infant_mortality/infant_mortality_cohort.rds"
    
    # Child birth date filters the cohort by age
    child_birth_date_min: "01/01/2011"
    child_birth_date_max: "31/12/2020"

    # The cohort is allowed to be unregistered for this many days 
    # in this period
    child_live_slack_days: 31

   # Postal code link to homes will  be considered on this target date
    postcode_target_date: "31/12/2023"
    # Neighbourhood geo link to homes will be considered on this target date
    gwb_target_date: "31/12/2023"
    # Corop geo link to homes will be considered on this target date
    corop_target_date: "31/12/2023"
    
    # Income will be deflated to cpi_base_year euros.
    cpi_base_year: 2020
    
    # Parent income year range
    parent_income_year_min: 2014
    parent_income_year_max: 2018
    
    # Parent wealth year range
    parent_wealth_year_min: 2011
    parent_wealth_year_max: 2020
    
    # remove gestational age at given days
    cut_off_days_min: 168
    cut_off_days_max: 294
    
    # when we measure the household composition of the child
    childhood_home_age: 0
    
  file_locations:
    # The data folder is the root folder of the cbs microdata tables
    data_folder: "G:/"
    # The scratch folder is used to write intermediate output
    scratch_folder: "scratch/newborns"
    
    # path to the cbs microdata
    gba_data: "Bevolking/GBAPERSOONTAB/2023/GBAPERSOON2023TABV1.sav"
    gbaao_data: "Bevolking/GBAADRESOBJECTBUS/GBAADRESOBJECT2023BUSV1.sav"
    kind_data: "Bevolking/KINDOUDERTAB/KINDOUDER2023TABV1.sav"
    postcode_data: "BouwenWonen/VSLPOSTCODEBUS/VSLPOSTCODEBUSV2024031.sav"
    vslgwb_data: "BouwenWonen/VSLGWBTAB/VSLGWB2023TAB03V1.sav"
    household_data: "Bevolking/GBAHUISHOUDENSBUS/GBAHUISHOUDENS2023BUSV1.sav"
    
    # perined data
    # perined_data: "H:/David/perined.rds" # old perined data
    perined_data: 'resources/8151_PERINED.rds'
    
    # resources
    cpi_index_data: "resources/Consumentenprijzen__prijsindex_2015_100_14112022_221558.xlsx"
    migration_data: "K:/Utilities/Code_Listings/SSBreferentiebestanden/LANDAKTUEELREFV11.SAV"
    corop_data: "K:/Utilities/HULPbestanden/GebiedeninNederland/Gemeenten en COROP vanaf 1981.xlsx"
    birthweight_data: "resources/Hoftiezer_Geboortegewicht curves.xlsx"
    boys_sheet: "Tabel jongens"
    girls_sheet: "Tabel meisjes"
    opleiding_data: "K:/Utilities/Code_Listings/SSBreferentiebestanden/OPLEIDINGSNRREFV34.SAV"
    cto_data: "K:/Utilities/Code_Listings/SSBreferentiebestanden/CTOREFV12.SAV"
  
